FROM node:22.12-alpine

WORKDIR /usr/app

COPY package*.json ./

RUN npm install --force

COPY . .

ENV HOSTNAME="0.0.0.0"

ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true

CMD [ "npm", "run", "dev" ]